### ISSUE TITLE
https://github.com/cra-ros-pkg/robot_localization.git

### ISSUE THREAD

**Issue by speronig** [Hypha-ROS/hypha-racecar#11]
hi when I type 'https://github.com/cra-ros-pkg/robot_localization.git' in the terminal I get this response:

remote: Repository not found.
fatal: repository 'https://github.com/cre-ros-pkg/robot_localization.git/' not found

why is this happening?

thank you

**Comment by gstavrinos** [comment]
Check your spelling.
