### ISSUE TITLE
Copy error messages

### ISSUE THREAD

**Issue by speronig** [Hypha-ROS/hypha-racecar#12]
hi I am trying to upload the code to the arduino nano but it is giving me all these copy error messages. I'm kinda new to arduino and I was wondering if anyone knew how to solve it. 
Thank you

![error](https://user-images.githubusercontent.com/49005827/55831032-359a7580-5ae0-11e9-8cb7-d9a6abdea21f.PNG)

**Comment by haochihlin** [comment]
Hi @speronig,

If you are using GY85 or razor-imu, I suggest you follow the tutorial in the following link:
http://wiki.ros.org/razor_imu_9dof

Or I remember our documentation should also mention how to load the firmware to arduino.

Cheers,
HaoChih, Lin

**Comment by speronig** [comment]
Hi @haochihlin ,
Thank you for your answer. I am using a GY-85, and even after following the tutorial I still get the same mistake. Could it be because I'm using an Arduino Nano instead of a Pro like is said in the tutorial?

Thank you

**Comment by speronig** [comment]
Nevermind @haochihlin  I made a rookie mistake.
