### ISSUE TITLE
Odroid xu4

### ISSUE THREAD

**Issue by speronig** [Hypha-ROS/hypha-racecar#13]
Hi i'm trying to establish the power connection for the odroid, however i'm having issues because it can't connect to the vcn. I am using virtual box, does that have anything to do with it? what could be wrong?

thank you

**Comment by haochihlin** [comment]
Hi
I am not sure what the 'vcn' stands for?
In addition, I have no idea the relationship between power connection and virtualbox...

**Comment by haochihlin** [comment]
If you are talking about the VNC setting, please refer the page 15 in the tutorial document:
https://github.com/Hypha-ROS/hypharos_racecar/blob/ver.1-release/document/Hypha-ROS-RaceCar-Tutorial_V1.1.pdf

**Comment by speronig** [comment]
Hi, sorry I did the steps on page 15, however regarding the steps on page 16, when I try to connect to the odroid from Remmina, it says 'unable to connect to VNC server'. Does the odroid need any installation prior to these steps?

**Comment by haochihlin** [comment]
Hi
I think if you used the odroid image we provided on the github, I would say it will be OK.
You could try to reset the VNC settings with monitor and test it again.
If it is still not working properly, I think you need to ask ubuntu or odroid community directly.
