### ISSUE TITLE
CLaserOdometry2D.cpp 

### ISSUE THREAD

**Issue by r290085** [Hypha-ROS/hypha-racecar#14]
您好: 
首先，我發現mapir-ros-pkgs這個pkg已經不支援而且catkin_make會報錯，所以我使用rf2o_laser_odometry這個更新過的pkg可以成功編譯ws.

之後我按照toutorial_V1.1 replace rf2o檔案卻無法再次成功編譯ws. 
Error顯示在CLaserOdometry2D.cpp 這個取代過的檔案. 
我想是否因為其他pkg的更新導致取代檔案已經無法使用?請問我該如何修改呢 謝謝!

**Comment by haochihlin** [comment]
你好
確實像你所描述的 更新版的rf2o_laser_odometry應該可行

至於你說的compile issue 我建議你先catkin clean後 再重新compile

**Comment by r290085** [comment]
你好 感謝你的回覆
另外想再請教使用gmapping建置地圖的問題。
我目前使用的是gmapping建圖，車子在行進及轉彎時必須非常慢否則會產生地圖重疊或偏移，請問文件裡提供的地圖也是用gmapping建置的嗎? 謝謝!
