### ISSUE TITLE
Error while running Test_gmapping.launch  file

### ISSUE THREAD

**Issue by MahnoorZaghum** [Hypha-ROS/hypha-racecar#15]
Hello! I am having this error continuously while running Test_gmapping.launch file. Btw I am new to ROS and trying to build your project.
![image](https://user-images.githubusercontent.com/41859528/56862252-6c1e2e80-69c2-11e9-8d7e-de24a13fca10.png)

Any help will be highly appreciated.

**Comment by haochihlin** [comment]
Hi
For your case, it's hard for me to figure out the exact cause.
Maybe the issue came from the rplidar driver.
