### ISSUE TITLE
/move_base_node/NavfnROS/plan

### ISSUE THREAD

**Issue by 001SCH** [Hypha-ROS/hypha-racecar#17]
Hi,I wonder if / move_base_node/NavfnROS/plan belongs to global_planner?
And I couldn't find the location in the code where it was published，I hope you could solve my problem.

**Comment by haochihlin** [comment]
Hi
As I recall correctly, then yes, move_base_node/NavfnROS/plan belongs to global_planne.
The path was published by standard move_base plugin

**Comment by 001SCH** [comment]
Thank you for your answer. I have understood this implementation process. In addition, after I raised the speed to 2m/s, the steering of the car is not timely enough, easy to collide, how should this be solved?

**Comment by 001SCH** [comment]
Hi.
I'm sorry to bother you again. I don't quite understand the role of the Angle_gain parameter in L1_controller_v2.cpp. Why not directly use the predicted angle, but multiply it by a multiple? In addition, I have referred to MIT's paper on closed-loop prediction and still do not understand how to adjust the parameters. Do you have any good suggestions?

发送自 Windows 10 版邮件应用

发件人: Hao-Chih, Lin
发送时间: 2019年5月12日 3:15
收件人: Hypha-ROS/hypharos_racecar
抄送: 001SCH; Author
主题: Re: [Hypha-ROS/hypharos_racecar] /move_base_node/NavfnROS/plan (#17)

Hi
As I recall correctly, then yes, move_base_node/NavfnROS/plan belongs to global_planne.
The path was published by standard move_base plugin
