### ISSUE TITLE
  Car footprint cannot follow radar

### ISSUE THREAD

**Issue by 001SCH** [Hypha-ROS/hypha-racecar#18]
When my racecar is running, in rviz, the obstacles scanned by radar often change (because the car is moving), but the footprint of the car does not move,And no problem of TF transformation has been found.I guess there is a problem with rf2o, but there is no solution yet. Do you have any suggestions?

**Comment by haochihlin** [comment]
Hi @001SCH ,
I think the problem came from the rf2o pkg.
As I recalled correctly, they have released the new official rf2o pkg.
Unfortunately, I have neither a racecar nor time to test the latest version of rf2o pkg.
