### ISSUE TITLE
the relationship of Lfw & Vcmd

### ISSUE THREAD

**Issue by TangHengxuan** [Hypha-ROS/hypha-racecar#19]
May I ask why the variable Lfw equals to (Vcmd*2.24)/3.
I learnd from other pages that selected Lfw = Vcmd*2.24.
Thank you so much , I am confused a lot.  Looking forward to your answer！！

**Comment by haochihlin** [comment]
Hi @TangHengxuan ,
As you mentioned, the value depicted in the paper is Lfw = Vcmd2.24.
However, it assumed there is a closed loop controller on car velocity.
In racecar (ver.1), we can not measure the car velocity directly, so we tuned the Lfw value by trail and errors.
