### ISSUE TITLE
找不到文件imu_auto.py

### ISSUE THREAD

**Issue by DavidHan008** [Hypha-ROS/hypha-racecar#3]
<launch>
--
2 | <node name="imu_auto"   pkg="hypha_racecar"  type="imu_auto.py" output="screen">

找不到文件imu_auto.py

**Comment by haochihlin** [comment]
Hi @DavidHan008 
the file "imu_auto.py" could be found in "hypha-racecar/script/".
I guess your problem is that you forgot to change the permission of the file to "executable".
You could try $ sudo chmod 755 imu_auto.py

**Comment by haochihlin** [comment]
I guess that this issue has been solved !
