### ISSUE TITLE
VMWare link not working

### ISSUE THREAD

**Issue by swapdha** [Hypha-ROS/hypha-racecar#5]
VMWare Image：
https://drive.google.com/drive/folders/0B-yq9HXd5lDkRGNJUm9KR0h0VEU
Its  not working,it show error.

**Comment by haochihlin** [comment]
Hi @swapdha 
Sorry for the late reply.
The VMWare image is too big and in fact, there is no special settings inside the image (just a standard ubuntu 16.04 with ROS Kinetic and hypharos_racecar pkg), so we decided to remove it!

We are considering providing docker or virtualbox OVA file as an alternative.

Cheers.

**Comment by swapdha** [comment]
Hi@jim
when will the docker or Virtual OVA file will be provided.
