### ISSUE TITLE
Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100223 timeout was 0.1.

### ISSUE THREAD

**Issue by Maxesss** [Hypha-ROS/hypha-racecar#7]
Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100223 timeout was 0.1.
查看了一下 rosrun tf view_frame map跟odom沒有被amcl發出

**Comment by haochihlin** [comment]
Hi @Maxesss 
Based on my experience, the cause of this issue generally came from "scan" topic.
Could you please check if the scan topic is published or not?
$ rostopic hz /scan

**Comment by haochihlin** [comment]
I supposed this issue has been solved!

**Comment by hakancan14** [comment]
> Merhaba @Maxesss Tecrübelerime dayanarak, bu sorunun nedeni genellikle "tarama" konusundan geldi. Lütfen tarama konusunun yayınlanıp yayınlanmadığını kontrol eder misiniz? $ rostopik hz /taram
i got the same error. When I run this code it says 'no new messages'. What should I do
