### ISSUE TITLE
IMU to Odroid XU4

### ISSUE THREAD

**Issue by subodh-malgonde** [Hypha-ROS/hypha-racecar#8]
First of all, thank you for maintaining this repository 👍 . I am building a 1/10 scale autonomous but I am constrained on budget. This repository is exactly what I needed.

I was looking at the [Hypha ROS RaceCar Tutorial V1.1.pdf](https://github.com/Hypha-ROS/hypharos_racecar/blob/ver.1-release/document/Hypha-ROS-RaceCar-Tutorial_V1.1.pdf) and I noticed that you use an Arduino Nano as an interface between the GY85 IMU and Odroid XU4. If I use a [Razor 9DOF IMU](https://www.sparkfun.com/products/14001) which has a micro USB slot, can I simply use a microUSB to USB connector and connect the IMU to the USB hub?

**Comment by haochihlin** [comment]
Hi 
Thank you for being interested in this repo.
For the IMU, yes, in our prototype version, we used Razor 9DOF IMU for yaw estimation.
The reason we adopt gy85 is because it is much cheaper :D
